version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: springboot-mysql
    restart: always
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: sa
      MYSQL_PASSWORD: mysqlpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
